apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-stream-api
  namespace: movie-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-stream-api
  template:
    metadata:
      labels:
        app: movie-stream-backend
    spec:
      containers:
        - name: backend
          image: paularinze/movie-stream-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: movie-stream-config
            - secretRef:
                name: movie-stream-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readnessProbe:
            httpGet:
            path: /
            port: 5000
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "20Mi"

