apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-stream-backend
  namespace: movie-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-stream-backend
  template:
    metadata:
      labels:
        app: movie-stream-backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/movie-stream-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DATABASE_NAME
              value: "movie-stream"
            - name: BASE_PROMPT_TEMPLATE
              value: "Return a response using one of these words: {rankings}..."
            - name: RECOMENDED_MOVIE_LIMIT
              value: "5"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:5173,http://localhost:8080"
            - name: GIN_MODE
              value: "release"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: movie-stream-backend-secrets
                  key: MONGODB_URI
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: movie-stream-backend-secrets
                  key: OPENAI_API_KEY
            - name: SECRET_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: movie-stream-backend-secrets
                  key: SECRET_REFRESH_KEY
