apiVersion: v1
kind: Secret
metadata:
  name: movie-stream-backend-secrets
  namespace: movie-stream
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://arinzennajipaul:<password>@cluster.mongodb.net"
  OPENAI_API_KEY: "<your_openai_api_key>"
  SECRET_REFRESH_KEY: "your_refresh_secret_key_here"
