apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-stream-frontend
  namespace: movie-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-stream-frontend
  template:
    metadata:
      labels:
        app: movie-stream-frontend
    spec:
      containers:
        - name: frontend
          image: paularinze/movie-stream-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: movie-stream-config
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readnessProbe:
            httpGet:
            path: /
            port: 80
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "20Mi"

