apiVersion: v1
kind: Service
metadata:
  name: movie-stream-frontend
  namespace: movie-stream
spec:
  selector:
    app: movie-stream-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
