apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-stream-config
  namespace: movie-stream
data:
  PORT: "8080"
  GIN_MODE: "release"
  DATABASE_NAME: "movie-stream"
  RECOMENDED_MOVIE_LIMIT: "5"
  ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173,http://localhost:8080"
  BASE_PROMPT_TEMPLATE: "Return a response using one of these words: {rankings}. The response should be a single word and should not contain any other text. The response should be based on any of the following review:"
  VITE_API_URL: "http://movie-stream-backend.movie-stream.svc.cluster.local:5000"

