apiVersion: v1
kind: Secret
metadata:
  name: movie-stream-secrets
  namespace: movie-stream
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://arinzennajipaul:<db_password>@cluster0.wroan.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  OPENAI_API_KEY: "<your_openai_api_key>"
  SECRET_REFRESH_KEY: "your_refresh_secret_key_here"
