name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
          

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./server/movie-stream-api
          file: ./server/movie-stream-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-stream-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/movie-stream-api:cache
          cache-to: type=inline
      
      - name: Scan Backend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/movie-stream-api:latest'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./clent/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-stream-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/movie-stream-frontend:cache
          cache-to: type=inline

      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/movie-stream-frontend:latest'
          format: 'table'
          exit-code: '0' # Fail the workflow if vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      


    
      